#ifndef SNIFFERCOMMIT_DOMAIN_ERROR_CODES_HPP
#define SNIFFERCOMMIT_DOMAIN_ERROR_CODES_HPP

#include <cstdint>

namespace sniffercommit::domain {

enum class ExitCode : std::uint8_t {
  SUCCESS = 0,
  GENERAL_ERROR = 1,
  INVALID_ARGUMENTS = 2,
  CONFIG_ERROR = 3,
  CHECK_FAILURE = 4,
  FORMAT_FAILURE = 5,
  MISSING_DEPENDENCY = 6,
  NOT_A_GIT_REPO = 7,
  FILESYSTEM_ERROR = 8,
  HOOK_INSTALL_ERROR = 9,
  WORKFLOW_GENERATION_ERROR = 10,
  TOOLCHAIN_INSTALL_ERROR = 11,
  UNSUPPORTED_PLATFORM = 12,
  UNSUPPORTED_CPP_STANDARD = 13,
  TEST_FAILURE = 14,
  TEST_BUILD_FAILURE = 15,
  TEST_TIMEOUT = 16,
  COVERAGE_THRESHOLD_NOT_MET = 17,
};

}  // namespace sniffercommit::domain

#endif
