#include "sniffercommit/generators/clang_tidy_generator.hpp"

#include <fmt/format.h>

#include <algorithm>
#include <cctype>
#include <stdexcept>
#include <string>
#include <vector>

namespace sniffercommit::generators {

namespace {

std::string normalize(std::string_view input) {
  std::string result;
  for (char chr : input) {
    result += static_cast<char>(std::tolower(static_cast<unsigned char>(chr)));
  }
  return result;
}

std::vector<std::string> preset_checks_impl(std::string_view preset) {
  auto norm = normalize(preset);
  if (norm == "minimal") {
    return {
        "cppcoreguidelines-*",
        "bugprone-*",
        "clang-analyzer-*",
        "-cppcoreguidelines-avoid-magic-numbers",
        "-cppcoreguidelines-pre-bounds-array-to-pointer-decay",
    };
  }
  if (norm == "standard") {
    return {
        "cppcoreguidelines-*",
        "bugprone-*",
        "clang-analyzer-*",
        "modernize-*",
        "performance-*",
        "-cppcoreguidelines-avoid-magic-numbers",
        "-cppcoreguidelines-pro-bounds-array-to-pointer-decay",
        "-modernize-use-trailing-return-type",
    };
  }
  if (norm == "strict") {
    return {
        "*",
        "-abseil-*",
        "-altera-*",
        "-fuchsia-*",
        "-llvm-*",
        "-zircon-*",
        "-google-readability-todo",
        "-readability-identifier-length",
        "-cppcoreguidelines-avoid-magic-numbers",
        "-cppcoreguidelines-pro-bounds-array-to-pointer-decay",
        "-modernize-use-trailing-return-type",
    };
  }
  if (norm == "custom") {
    return {};
  }
  throw std::runtime_error("Unknown tidy preset: " + std::string(preset));
}

std::string severity_warnings_as_errors(std::string_view sev) {
  auto norm = normalize(sev);
  if (norm == "note") return "";
  if (norm == "warning") return "clang-diagnostic-*";
  if (norm == "error") return "*";
  return "*";
}

}  // namespace

std::vector<std::string> get_preset_checks(std::string_view preset) {
  return preset_checks_impl(preset);
}

std::string generate_clang_tidy(std::string_view preset, std::string_view severity,
                                int header_filter_level) {
  auto checks = preset_checks_impl(preset);
  if (checks.empty() && normalize(preset) == "custom") {
    throw std::runtime_error("Custom preset requires at least one explicit check");
  }

  std::string check_str;
  for (size_t i = 0; i < checks.size(); ++i) {
    if (i > 0) check_str += ",";
    check_str += checks.at(i);
  }

  std::string header_filter;
  switch (header_filter_level) {
    case 0:
      header_filter = "\"^(?!/usr)(?!/opt)(?!/System).*\"";
      break;
    case 1:
      header_filter = R"("^\\.\\./.*")";
      break;
    case 2:
    default:
      header_filter = "\".*\"";
      break;
  }

  auto wae = severity_warnings_as_errors(severity);
  auto norm_preset = normalize(preset);

  return fmt::format(
      R"(---
# Generated by sniffercommit | DO NOT EDIT manually
# Preset: {}
# Severity threshold: {}

Checks: "{}"
WarningsAsErrors: '{}'
HeaderFilterRegex: {}
FormatStyle: file

CheckOptions:
  - key: readability-identifier-naming.NamespaceCase
    value: lower_case
  - key: readability-identifier-naming.ClassCase
    value: CamelCase
  - key: readability-identifier-naming.FunctionCase
    value: camelBack
  - key: readability-identifier-naming.VariableCase
    value: lower_case
  - key: readability-identifier-naming.MemberCase
    value: lower_case
  - key: readability-identifier-naming.MemberSuffix
    value: _
  - key: cppcoreguidelines-special-member-functions.AllowSoleDefaultDtor
    value: 1
  - key: cppcoreguidelines-avoid-magic-numbers.IgnorePowersOf2
    value: 1
  - key: modernize-loop-convert.MaxCopySize
    value: 16
  - key: modernize-pass-by-value.IncludeStyle
    value: llvm
  - key: modernize-use-default-member-init.UseAssignment
    value: 1
  - key: performance-unnecessary-value-param.AllowedTypes
    value: "std::.*;llvm::.*;fmt::.*"
  - key: bugprone-exception-escape.FunctionThatShouldNotThrow
    value: "main;wmain;WinMain;wWinMain"
  - key: readability-function-cognitive-complexity.Threshold
    value: 25
  - key: readability-function-cognitive-complexity.DescribeBasicIncrements
    value: 0

...
)",
      norm_preset, normalize(severity), check_str, wae, header_filter);
}

}  // namespace sniffercommit::generators
