#include "sniffercommit/generators/cmake_generator.hpp"

#include <fmt/format.h>

#include <algorithm>
#include <cctype>
#include <string>
#include <vector>

namespace sniffercommit::generators {

namespace {

std::string normalize(std::string_view input) {
  std::string result;
  for (char chr : input) {
    result += static_cast<char>(std::tolower(static_cast<unsigned char>(chr)));
  }
  return result;
}

std::string target_type_cmake(std::string_view type) {
  auto norm = normalize(type);
  if (norm == "executable" || norm == "exe") return "EXECUTABLE";
  if (norm == "static" || norm == "staticlib") return "STATIC";
  if (norm == "shared" || norm == "sharedlib") return "SHARED";
  if (norm == "header-only" || norm == "interface") return "INTERFACE";
  return "EXECUTABLE";
}

std::string cpp_standard_val(std::string_view std_str) {
  auto norm = normalize(std_str);
  if (norm == "17" || norm == "c++17") return "17";
  if (norm == "23" || norm == "c++23") return "23";
  return "20";
}

}  // namespace

std::string generate_cmake_lists(std::string_view project_name, std::string_view cpp_standard,
                                 std::string_view target_type, bool enable_testing,
                                 bool enable_sanitizers, bool enable_warnings,
                                 bool enable_clang_tidy,
                                 const std::vector<std::string>& dependencies) {
  std::string cmake;
  cmake += fmt::format("# Generated by sniffercommit\n");
  cmake += fmt::format("# Project: {}\n\n", project_name);
  cmake += "cmake_minimum_required(VERSION 3.20)\n";
  cmake += fmt::format("project({} VERSION 0.1.0 LANGUAGES CXX)\n\n", project_name);

  cmake += fmt::format("set(CMAKE_CXX_STANDARD {})\n", cpp_standard_val(cpp_standard));
  cmake += "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
  cmake += "set(CMAKE_CXX_EXTENSIONS OFF)\n";
  cmake += "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n\n";

  if (!dependencies.empty()) {
    cmake += "# Dependencies\n";
    cmake += "include(FetchContent)\n";
    for (const auto& dep : dependencies) {
      // dep format: "name:url:tag"
      auto first_colon = dep.find(':');
      if (first_colon == std::string::npos) continue;
      auto second_colon = dep.find(':', first_colon + 1);
      std::string name = dep.substr(0, first_colon);
      std::string url = dep.substr(first_colon + 1, second_colon - first_colon - 1);
      std::string tag = (second_colon != std::string::npos) ? dep.substr(second_colon + 1) : "main";
      cmake += fmt::format("FetchContent_Declare(\n  {}\n", name);
      cmake += fmt::format("  GIT_REPOSITORY {}\n", url);
      cmake += fmt::format("  GIT_TAG {}\n)\n", tag);
    }
    cmake += "\n";
  }

  auto target = target_type_cmake(target_type);
  if (target == "INTERFACE") {
    cmake += fmt::format("add_library({} INTERFACE)\n", project_name);
    cmake += fmt::format("target_include_directories({} INTERFACE\n", project_name);
    cmake += "  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>\n";
    cmake += "  $<INSTALL_INTERFACE:include>\n)\n\n";
  } else if (target == "EXECUTABLE") {
    cmake += "file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS \"src/*.cpp\" \"src/*.cc\")\n";
    cmake += fmt::format("add_executable({} ${{SOURCES}})\n", project_name);
    cmake += fmt::format("target_include_directories({} PUBLIC\n", project_name);
    cmake += "  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>\n";
    cmake += "  $<INSTALL_INTERFACE:include>\n)\n\n";
  } else {
    cmake += "file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS \"src/*.cpp\" \"src/*.cc\")\n";
    cmake += fmt::format("add_library({} {} ${{SOURCES}})\n", project_name, target);
    cmake += fmt::format("target_include_directories({} PUBLIC\n", project_name);
    cmake += "  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>\n";
    cmake += "  $<INSTALL_INTERFACE:include>\n)\n\n";
  }

  if (enable_warnings && target != "INTERFACE") {
    cmake += "if(CMAKE_CXX_COMPILER_ID MATCHES \"GNU|Clang\")\n";
    cmake += fmt::format("  target_compile_options({} PRIVATE -Wall -Wextra -Wpedantic)\n",
                         project_name);
    cmake += "endif()\n\n";
  }

  if (enable_sanitizers && target != "INTERFACE") {
    cmake += "if(CMAKE_CXX_COMPILER_ID MATCHES \"GNU|Clang\")\n";
    cmake += fmt::format(
        "  target_compile_options({} PRIVATE "
        "\"$<$<CONFIG:Debug>:-fsanitize=address,undefined>\")\n",
        project_name);
    cmake += fmt::format(
        "  target_link_options({} PRIVATE \"$<$<CONFIG:Debug>:-fsanitize=address,undefined>\")\n",
        project_name);
    cmake += "endif()\n\n";
  }

  if (enable_clang_tidy && target != "INTERFACE") {
    cmake += "find_program(CLANG_TIDY_EXE NAMES clang-tidy)\n";
    cmake += "if(CLANG_TIDY_EXE)\n";
    cmake += fmt::format("  set_target_properties({} PROPERTIES\n", project_name);
    cmake += "    CXX_CLANG_TIDY \"${CLANG_TIDY_EXE}\"\n";
    cmake += "  )\n";
    cmake += "endif()\n\n";
  }

  if (enable_testing) {
    cmake += "enable_testing()\n";
    cmake += "add_subdirectory(tests)\n\n";
  }

  return cmake;
}

}  // namespace sniffercommit::generators
