#include "metis/generators/conan_generator.hpp"

#include <fmt/format.h>

#include <algorithm>
#include <cctype>
#include <string>
#include <vector>

namespace metis::generators {

namespace {

std::string dep_name(const std::string& dep) {
  auto pos = dep.find(':');
  return pos != std::string::npos ? dep.substr(0, pos) : dep;
}

std::string dep_conan_name(const std::string& dep) {
  auto name = dep_name(dep);
  std::string result;
  for (char c : name) {
    result += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
  }
  return result;
}

}  // namespace

std::string generate_conanfile(std::string_view project_name, bool enable_testing,
                               const std::vector<std::string>& dependencies) {
  std::string conan;
  conan += "# Generated by metis\n";
  conan += fmt::format("# Project: {}\n\n", project_name);
  conan += "from conan import ConanFile\n";
  conan += "from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout\n";
  conan += "from conan.tools.files import copy\n";
  conan += "import os\n\n\n";

  std::string safe_name;
  for (char c : project_name) {
    safe_name += (c == '-') ? '_' : c;
  }
  conan += fmt::format("class {}Conan(ConanFile):\n", safe_name);
  conan += fmt::format("    name = \"{}\"\n", project_name);
  conan += "    version = \"0.1.0\"\n";
  conan += "    license = \"MIT\"\n";
  conan += "    settings = \"os\", \"compiler\", \"build_type\", \"arch\"\n";
  conan += "    exports_sources = \"CMakeLists.txt\", \"cmake/*\", \"include/*\", \"src/*\"\n\n";

  conan += "    def layout(self):\n";
  conan += "        cmake_layout(self)\n\n";

  conan += "    def requirements(self):\n";
  if (dependencies.empty()) {
    conan += "        pass\n";
  } else {
    for (const auto& dep : dependencies) {
      auto name = dep_conan_name(dep);
      conan += fmt::format("        self.requires(\"{}/0.1.0\")\n", name);
    }
  }

  conan += "\n    def build_requirements(self):\n";
  if (enable_testing) {
    conan += "        self.test_requires(\"gtest/1.15.2\")\n";
  } else {
    conan += "        pass\n";
  }

  conan += "\n    def generate(self):\n";
  conan += "        tc = CMakeToolchain(self)\n";
  conan += "        tc.generate()\n";
  conan += "        deps = CMakeDeps(self)\n";
  conan += "        deps.generate()\n\n";

  conan += "    def build(self):\n";
  conan += "        cmake = CMake(self)\n";
  conan += "        cmake.configure()\n";
  conan += "        cmake.build()\n\n";

  conan += "    def package(self):\n";
  conan += fmt::format(
      "        copy(self, \"LICENSE\", src=self.source_folder, "
      "dst=os.path.join(self.package_folder, \"licenses\"))\n");
  conan += "        cmake = CMake(self)\n";
  conan += "        cmake.install()\n\n";

  conan += "    def package_info(self):\n";
  conan += fmt::format("        self.cpp_info.libs = [\"{}\"]\n", project_name);

  return conan;
}

}  // namespace metis::generators
