#include "sniffercommit/application/install_use_case.hpp"

#include <fmt/format.h>
#include <unistd.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <random>
#include <sstream>
#include <string>
#include <string_view>
#include <system_error>
#include <utility>

#include "sniffercommit/domain/config.hpp"
#include "sniffercommit/domain/workflow.hpp"

namespace sniffercommit::application {

namespace {

// Escapes special regex characters in a string for use in grep patterns.
// Used to convert exclude_paths (e.g. "build/") into safe grep patterns.
std::string regex_escape(const std::string& str) {
  std::string out;
  out.reserve(str.size() * 2);
  for (char chr : str) {
    switch (chr) {
      case '.':
      case '*':
      case '?':
      case '[':
      case ']':
      case '^':
      case '$':
      case '(':
      case ')':
      case '{':
      case '}':
      case '|':
      case '\\':
      case '+':
        out += '\\';
        break;
      default:
        break;
    }
    out += chr;
  }
  return out;
}

constexpr std::string_view k_version = "0.3.20";

// Generates the pre-commit hook bash script.
// The hook:
//   1. Checks for SKIP_SNIFFERCOMMIT env var (skip mechanism)
//   2. Verifies sniffercommit is in PATH
//   3. Gets staged files via git diff --cached
//   4. Filters out excluded paths via grep -vE
//   5. Runs sniffercommit run --staged on the filtered list
//
// The exclude pattern is built from config.exclude_paths and escaped
// for grep's regex syntax.
std::string generate_hook_content(const domain::config::ProjectConfig& cfg) {
  std::string exclude_pattern = "^.NO_MATCH$";
  if (!cfg.exclude_paths.empty()) {
    std::ostringstream oss;
    for (size_t i = 0; i < cfg.exclude_paths.size(); ++i) {
      if (i > 0) {
        oss << "|";
      }
      oss << regex_escape(cfg.exclude_paths.at(i));
    }
    exclude_pattern = "(" + oss.str() + ")";
  }

  return fmt::format(
      R"(#!/usr/bin/env bash
# Generated by sniffercommit v{} | DO NOT EDIT MANUALLY
# Project: {}
set -euo pipefail

if [[ -n "${{SKIP_SNIFFERCOMMIT:-}}" ]]; then
    echo "[sniffercommit] skipped via SKIP_SNIFFERCOMMIT"
    exit 0
fi


if ! command -v sniffercommit &>/dev/null; then
    echo "[sniffercommit] ERROR: sniffercommit not found in PATH" >&2
    echo "[sniffercommit] Install it or run: git commit --no-verify" >&2
    exit 1
fi


FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -vE '{}' || true)

if [[ -z "$FILES" ]]; then
    exit 0
fi

if [[ -n "${{SNIFFERCOMMIT_VERBOSE:-}}" ]]; then
    echo "[sniffercommit] checking $(echo "$FILES" | wc -l) file(s)..."
fi

START_TIME=$(date +%s)

# Run sniffercommit on staged files
sniffercommit run --staged

EXIT_CODE=$?

if [[ -n "${{SNIFFERCOMMIT_TIMING:-}}" ]]; then
    END_TIME=$(date +%s)
    ELAPSED=$((END_TIME - START_TIME))
    echo "[sniffercommit] completed in ${{ELAPSED}}s"
fi

exit $EXIT_CODE
)",
      k_version, cfg.project_name, exclude_pattern);
}

// Validates bash script syntax using `bash -n` (no-exec mode).
// Writes the content to a temp file, runs bash -n, then cleans up.
// This prevents installing broken hooks that would fail silently.
// On Windows, always returns true (bash validation not available).
bool validate_bash_syntax(const std::string& content) {
#ifndef _WIN32
  char tmp_template[] = "/tmp/sniffercommit_hook_XXXXXX";
  int fd = ::mkstemp(tmp_template);
  if (fd == -1) {
    return false;
  }

  struct TempFileGuard {
    std::string path;
    int fd;
    explicit TempFileGuard(std::string p, int f) : path(std::move(p)), fd(f) {}
    ~TempFileGuard() {
      ::close(fd);
      std::error_code ec;
      std::filesystem::remove(path, ec);
    }
    TempFileGuard(const TempFileGuard&) = delete;
    TempFileGuard& operator=(const TempFileGuard&) = delete;
  };
  TempFileGuard guard(tmp_template, fd);

  {
    std::ofstream out(tmp_template);
    if (!out) {
      return false;
    }
    out << content;
    out.close();
    if (!out.good()) {
      return false;
    }
  }

  std::string cmd = "bash -n " + std::string(tmp_template) + " 2>/dev/null";
  return std::system(cmd.c_str()) == 0;
#else
  (void)content;
  return true;
#endif
}

}  // namespace

InstallUseCase::InstallUseCase(std::unique_ptr<domain::ports::IFileSystem> file_system,
                               std::unique_ptr<domain::ports::IGitRepository> git_repo)
    : file_system_(std::move(file_system)), git_repo_(std::move(git_repo)) {}

// Installs pre-commit hook and/or CI workflow files.
//
// Three independent install paths based on config:
//   1. Local hook (.git/hooks/pre-commit) — if generate_local_hook
//   2. GitHub Actions (.github/workflows/sniffercommit.yml) — if generate_gha
//   3. GitLab CI (.gitlab-ci.yml) — if generate_gitlab_ci
//
// Each path: validate → create dirs → write file → set permissions (Unix only).
// Hook permissions are 755 (rwxr-xr-x) so git can execute it.
InstallResult InstallUseCase::execute(const std::filesystem::path& repo_root,
                                      const domain::config::ProjectConfig& cfg) {
  InstallResult result;

  if (cfg.generate_local_hook) {
    auto hook_content = generate_hook_content(cfg);

    if (!validate_bash_syntax(hook_content)) {
      result.error_message = "Generated hook failed syntax validation";
      return result;
    }

    auto hooks_dir = repo_root / ".git" / "hooks";
    if (!file_system_->create_directories(hooks_dir)) {
      result.error_message = "Failed to create hooks directory";
      return result;
    }

    auto hook_path = hooks_dir / "pre-commit";
    if (!file_system_->write_file(hook_path, hook_content)) {
      result.error_message = "Failed to install pre-commit hooks";
      return result;
    }

#ifndef _WIN32
    if (!file_system_->set_permissions(
            hook_path,
            std::filesystem::perms::owner_all | std::filesystem::perms::group_read |
                std::filesystem::perms::group_exec | std::filesystem::perms::others_read |
                std::filesystem::perms::others_exec,
            std::filesystem::perm_options::replace)) {
      result.error_message = "Failed to set hook permissions";
      return result;
    }
#endif

    result.hook_installed = true;
    result.hook_path = (repo_root / ".git" / "hooks" / "pre-commit").string();
  }

  if (cfg.generate_gha) {
    domain::workflow::WorkflowConfig wf_cfg;
    auto wf_content = domain::workflow::generate_github_actions(cfg, wf_cfg);

    auto wf_dir = repo_root / ".github" / "workflows";
    if (!file_system_->create_directories(wf_dir)) {
      result.error_message = "Failed to create workflows directory";
      return result;
    }

    auto wf_path = wf_dir / "sniffercommit.yml";
    if (!file_system_->write_file(wf_path, wf_content)) {
      result.error_message = "Failed to write Github Action workflow";
      return result;
    }

    result.workflow_installed = true;
    result.workflow_path = wf_path.string();
  }

  if (cfg.generate_gitlab_ci) {
    domain::workflow::WorkflowConfig wf_cfg;
    wf_cfg.platform = domain::workflow::Platform::GitLabCI;
    auto wf_content = domain::workflow::generate_workflow(cfg, wf_cfg);

    auto wf_path = repo_root / ".gitlab-ci.yml";
    if (!file_system_->write_file(wf_path, wf_content)) {
      result.error_message = "Failed to write GitLab CI workflow";
      return result;
    }

    result.workflow_installed = true;
    result.workflow_path = wf_path.string();
  }

  return result;
}

}  // namespace sniffercommit::application
