#include "sniffercommit/application/install_use_case.hpp"

#include <fmt/format.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <random>
#include <sstream>
#include <string>
#include <system_error>
#include <utility>

#include "sniffercommit/domain/config.hpp"
#include "sniffercommit/domain/workflow.hpp"

namespace sniffercommit::application {

namespace {

std::string regex_escape(const std::string& str) {
  std::string out;
  out.reserve(str.size() * 2);
  for (char chr : str) {
    switch (chr) {
      case '\\':
      case '.':
      case '+':
      case '*':
      case '?':
      case '[':
      case ']':
      case '^':
      case '$':
      case '(':
      case ')':
      case '{':
      case '}':
      case '|':
      case '`':
      case '"':
      case '!':
      case '&':
      case ';':
      case '<':
      case '>':
      case '#':
      case '~':
      case '\n':
        out += '\\';
        break;
      default:
        break;
    }
    out += chr;
  }
  return out;
}

std::string generate_hook_content(const domain::config::ProjectConfig& cfg) {
  std::string exclude_pattern = "^.NO_MATCH$";
  if (!cfg.exclude_paths.empty()) {
    std::ostringstream oss;
    for (size_t i = 0; i < cfg.exclude_paths.size(); ++i) {
      if (i > 0) {
        oss << "|";
      }
      oss << regex_escape(cfg.exclude_paths.at(i));
    }
    exclude_pattern = "(" + oss.str() + ")";
  }

  return fmt::format(
      R"(#!/usr/bin/env bash
# Generated by sniffercommit v0.2.1 | DO NOT EDIT MANUALLY
# Project: {}
set -uo pipefail

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -vE '{}' || true)

if [[ -z "$FILES" ]]; then
    exit 0
fi

exec sniffercommit run --staged
)",
      cfg.project_name, exclude_pattern);
}

bool validate_bash_syntax(const std::string& content) {
#ifndef _WIN32
  struct TempFileGuard {
    std::filesystem::path path;
    explicit TempFileGuard(std::filesystem::path p) : path(std::move(p)) {}
    ~TempFileGuard() {
      std::error_code ec;
      std::filesystem::remove(path, ec);
    }
    TempFileGuard(const TempFileGuard&) = delete;
    TempFileGuard& operator=(const TempFileGuard&) = delete;
    TempFileGuard(TempFileGuard&&) = default;
    TempFileGuard& operator=(TempFileGuard&&) = default;
  };

  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_int_distribution<> dis(100000, 999999);
  auto temp_path = std::filesystem::temp_directory_path() /
                   fmt::format("sniffercommit_hook_check_{}.sh", dis(gen));

  TempFileGuard guard{temp_path};

  {
    std::ofstream out(temp_path);
    if (!out) {
      return false;
    }
    out << content;
    out.close();
    if (!out.good()) {
      return false;
    }
  }

  std::string cmd = "bash -n " + temp_path.string() + " 2>/dev/null";
  return std::system(cmd.c_str()) == 0;
#else
  (void)content;
  return true;
#endif
}

}  // namespace

InstallUseCase::InstallUseCase(std::unique_ptr<domain::ports::IFileSystem> file_system,
                               std::unique_ptr<domain::ports::IGitRepository> git_repo)
    : file_system_(std::move(file_system)), git_repo_(std::move(git_repo)) {}

InstallResult InstallUseCase::execute(const std::filesystem::path& repo_root,
                                      const domain::config::ProjectConfig& cfg) {
  InstallResult result;

  if (cfg.generate_local_hook) {
    auto hook_content = generate_hook_content(cfg);

    if (!validate_bash_syntax(hook_content)) {
      result.error_message = "Generated hook failed syntax validation";
      return result;
    }

    auto hooks_dir = repo_root / ".git" / "hooks";
    if (!file_system_->create_directories(hooks_dir)) {
      result.error_message = "Failed to create hooks directory";
      return result;
    }

    auto hook_path = hooks_dir / "pre-commit";
    if (!file_system_->write_file(hook_path, hook_content)) {
      result.error_message = "Failed to install pre-commit hooks";
      return result;
    }

#ifndef _WIN32
    if (!file_system_->set_permissions(
            hook_path,
            std::filesystem::perms::owner_all | std::filesystem::perms::group_read |
                std::filesystem::perms::group_exec | std::filesystem::perms::others_read |
                std::filesystem::perms::others_exec,
            std::filesystem::perm_options::replace)) {
      result.error_message = "Failed to set hook permissions";
      return result;
    }
#endif

    result.hook_installed = true;
    result.hook_path = (repo_root / ".git" / "hooks" / "pre-commit").string();
  }

  if (cfg.generate_gha) {
    domain::workflow::WorkflowConfig wf_cfg;
    auto wf_content = domain::workflow::generate_github_actions(cfg, wf_cfg);

    auto wf_dir = repo_root / ".github" / "workflows";
    if (!file_system_->create_directories(wf_dir)) {
      result.error_message = "Failed to create workflows directory";
      return result;
    }

    auto wf_path = wf_dir / "sniffercommit.yml";
    if (!file_system_->write_file(wf_path, wf_content)) {
      result.error_message = "Failed to write Github Action workflow";
      return result;
    }

    result.workflow_installed = true;
    result.workflow_path = wf_path.string();
  }

  return result;
}

}  // namespace sniffercommit::application
