#include "../include/sniffercommit/generator.hpp"

#include <fmt/format.h>

#include <sstream>
#include <string>

#include "fmt/base.h"

namespace sniffercommit {

std::string generate_local_hook(const Config& cfg) {
  std::string exclude_pattern = "^.NO_MATCH$";
  if (!cfg.exclude_paths.empty()) {
    std::ostringstream oss;
    for (size_t i = 0; i < cfg.exclude_paths.size(); ++i) {
      if (i > 0) oss << "|";
      oss << cfg.exclude_paths[i];
    }
    exclude_pattern = "(" + oss.str() + ")";
  }

  std::string execution_block;
  if (cfg.parallel) {
    execution_block = "declare -a PIDS=()\n\n";
    for (const auto& check : cfg.checks) {
      std::string cmd = check.command;
      for (const auto& arg : check.args) {
        cmd += " \"" + arg + "\"";
      }
      std::string patterns;
      for (const auto& p : check.patterns) {
        patterns += " \"" + p + "\"";
      }
      execution_block +=
          fmt::format("( run_check \"{}\" {} {} ) & PIDS+=($!)\n", check.name, cmd, patterns);
    }

    execution_block += R"DELIM(
if [[ ${#PIDS[@]} -gt 0 ]]; then
  EXIT_CODE=0
  for pid in "${PIDS[@]}"; do
    if ! wait "$pid"; then
      echo "[sniffercommit] [ERROR] Check failed (PID: $pid)" >&2
      EXIT_CODE=1
    fi
  done
  if [[ $EXIT_CODE -eq 0 ]]; then
    echo "[sniffercommit] [INFO] All checks passed."
  else
    echo "[sniffercommit] [ERROR] One or more checks failed."
  fi
  exit $EXIT_CODE
fi
)DELIM";
  } else {
    for (const auto& check : cfg.checks) {
      std::string cmd = check.command;
      for (const auto& arg : check.args) cmd += " \"" + arg + "\"";
      std::string patterns;
      for (const auto& p : check.patterns) patterns += " \"" + p + "\"";
      execution_block +=
          fmt::format("run_check \"{}\" {} {} || EXIT_CODE=$?\n", check.name, cmd, patterns);
    }
    execution_block += "exit $EXIT_CODE\n";
  }

  return fmt::format(
      "#!/usr/bin/env bash\n"
      "# Generated by sniffercommit v0.1.0 | DO NOT EDIT MANUALLY\n"
      "# Execution mode: {}\n"
      "# Project: {}\n\n"
      "set -uo pipefail\n\n"
      "FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -vE '{}' "
      "|| true)\n"
      "if [[ -z \"$FILES\" ]]; then\n"
      "  echo \"[sniffercommit] No staged files to check.\"\n"
      "  exit 0\n"
      "fi\n\n"
      "# Filter files by glob patterns (bash-style)\n"
      "filter_by_patterns() {{\n"
      "  local files=\"$1\"; shift\n"
      "  local patterns=(\"$@\")\n"
      "  # If no patterns, return all files\n"
      "  if [[ ${{#patterns[@]}} -eq 0 ]]; then\n"
      "    echo \"$files\"\n"
      "    return\n"
      "  fi\n"
      "  # Filter: keep files matching ANY pattern\n"
      "  echo \"$files\" | while IFS= read -r file; do\n"
      "    [[ -z \"$file\" ]] && continue\n"
      "    for pattern in \"${{patterns[@]}}\"; do\n"
      "      # Use bash glob matching: [[ $file == $pattern ]]\n"
      "      if [[ \"$file\" == $pattern ]]; then\n"
      "        echo \"$file\"\n"
      "        break\n"
      "      fi\n"
      "    done\n"
      "  done\n"
      "}}\n\n"
      "# Run check with safe file iteration (no xargs complexity)\n"
      "run_check() {{\n"
      "  local name=\"$1\"; shift\n"
      "  local cmd=\"$1\"; shift\n"
      "  local patterns=(\"$@\")\n"
      "  echo \"[sniffercommit] [$(date +%T)] [INFO] Running: $name\"\n"
      "  \n"
      "  # Filter files by patterns\n"
      "  local filtered\n"
      "  filtered=$(filter_by_patterns \"$FILES\" \"${{patterns[@]}}\")\n"
      "  \n"
      "  if [[ -z \"$filtered\" ]]; then\n"
      "    echo \"[sniffercommit] [SKIP] No matching files for $name\"\n"
      "    return 0\n"
      "  fi\n"
      "  \n"
      "  # Run command on each file (safe for spaces/special chars)\n"
      "  local status=0\n"
      "  while IFS= read -r file; do\n"
      "    [[ -z \"$file\" ]] && continue\n"
      "    if ! \"$cmd\" \"$file\" 2>&1; then\n"
      "      status=$?\n"
      "    fi\n"
      "  done <<< \"$filtered\"\n"
      "  \n"
      "  # Normalize grep exit code: 1 = no match = success for linters\n"
      "  if [[ \"$cmd\" == \"grep\" && $status -eq 1 ]]; then\n"
      "    status=0\n"
      "  fi\n"
      "  \n"
      "  if [[ $status -ne 0 ]]; then\n"
      "    echo \"[sniffercommit] [WARN] $name exited with status $status\" "
      ">&2\n"
      "  fi\n"
      "  return $status\n"
      "}}\n\n"
      "EXIT_CODE=0\n"
      "{}",
      cfg.parallel ? "PARALLEL" : "SEQUENTIAL", cfg.project_name, exclude_pattern, execution_block);
}

std::string gha_escape(const std::string& value) {
  std::string escaped;

  for (char c : value) {
    if (c == '"') {
      escaped += "\\\"";
    } else {
      escaped += c;
    }
  }

  return escaped;
}

bool requires_clang_format(const Config& cfg) {
  for (const auto& check : cfg.checks) {
    if (check.command == "clang-format") {
      return true;
    }
  }

  return false;
}

std::string generate_github_actions(const Config& cfg) {
  std::string yml;

  yml += "name: sniffercommit\n\n";

  yml += "on:\n";
  yml += "  push:\n";
  yml += "    branches:\n";
  yml += "      - \"**\"\n\n";

  yml += "  pull_request:\n";
  yml += "    branches:\n";
  yml += "      - \"**\"\n\n";

  yml += "concurrency:\n";
  yml += "  group: sniffercommit-${{ github.ref }}\n";
  yml += "  cancel-in-progress: true\n\n";

  yml += "permissions:\n";
  yml += "  contents: read\n\n";

  yml += "jobs:\n";
  yml += "  checks:\n";
  yml += "    name: Run sniffercommit checks\n";
  yml += "    runs-on: ubuntu-latest\n";
  yml += "    timeout-minutes: 10\n\n";

  yml += "    steps:\n";

  yml += "      - name: Checkout repository\n";
  yml += "        uses: actions/checkout@v4\n";
  yml += "        with:\n";
  yml += "          fetch-depth: 0\n\n";

  if (requires_clang_format(cfg)) {
    yml += "      - name: Install clang-format\n";
    yml += "        run: |\n";
    yml += "          sudo apt-get update\n";
    yml += "          sudo apt-get install -y clang-format\n\n";
  }

  yml += "      - name: Make sniffercommit executable\n";
  yml += "        run: chmod +x ./sniffercommit\n\n";

  yml += "      - name: Run sniffercommit\n";
  yml += "        shell: bash\n";
  yml += "        run: |\n";
  yml += "          set -euo pipefail\n";
  yml += "          ./sniffercommit run --all-files --verbose\n";

  return yml;
}

}  // namespace sniffercommit
