#include "../include/sniffercommit/generator.hpp"
#include "fmt/base.h"
#include <fmt/format.h>
#include <string>

namespace sniffercommit {

std::string generate_local_hook(const Config& cfg) {
    std::string exclude_regex;
    for (const auto& ex : cfg.exclude_paths) {
        if (!exclude_regex.empty()) exclude_regex += "|";
        exclude_regex += ex;
    }
    if (exclude_regex.empty()) exclude_regex = "^.NO_MATCH$";

    std::string check_blocks;
    for (const auto& check : cfg.checks) {
        std::string args_str;
        for (const auto& a : check.args) args_str += " " + a;
        check_blocks += fmt::format(
            "run_check \"{}\" {} \"$FILES\" || EXIT_CODE=$?\n",
            check.name, check.command + args_str);
    }

    return fmt::format(
        "#!/usr/bin/env bash\n"
        "# Generated by sniffercommit | DO NOT EDIT MANUALLY\n"
        "set -euo pipefail\n\n"
        "FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -vE '{}' || true)\n"
        "if [ -z \"$FILES\" ]; then exit 0; fi\n\n"
        "EXIT_CODE=0\n"
        "echo \"Running {} pre-commit checks...\"\n"
        "{}\n"
        "exit $EXIT_CODE\n",
        exclude_regex, cfg.checks.size(), check_blocks);
}

std::string generate_github_actions(const Config& cfg) {
    std::string steps;
    for (const auto& check : cfg.checks) {
        std::string cmd = check.command;
        for (const auto& a : check.args) cmd += " " + a;
        steps += fmt::format(
            "      - name: {}\n"
            "        run: {}\n",
            check.name, cmd);
    }

    return fmt::format(
        "name: sniffercommit CI\n"
        "on: [pull_request, push]\n"
        "jobs:\n"
        "  pre-commit:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "{}\n",
        steps);
}

} // namespace sniffercommit
