#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

#include "../include/sniffercommit/argparser.hpp"
#include "../include/sniffercommit/config.hpp"
#include "../include/sniffercommit/generator.hpp"
#include "../include/sniffercommit/installer.hpp"

int main(int argc, char **argv) {

  using namespace sniffercommit;

  std::string config_path = ".sniffercommit.toml";
  bool show_version = false;

  ArgParser app("sniffercommit", "fast C++ powered pre-commit & CI generator");
  app.set_version("0.1.0")
      .add_option("-c", "--config", "Config file path", config_path)
      .add_flag("-v", "--version", "Show version", show_version)
      .add_subcommand("init", "Create default .sniffercommit.toml")
      .add_subcommand("install", "Generate & install .git/hooks/pre-commit")
      .add_subcommand("generate-gha", "output github actions workflow");

  if (!app.parse(argc, argv)) {
    return 0;
  }

  try {
    auto subcmd = app.get_subcommand();

    if (subcmd == "init") {
      std::ofstream out(config_path, std::ios::trunc);
      out << R"(# sniffercommit configuration - TOML format
# Generated by sniffercommit init

[project]
name = "my-project"

[[checks]]
name = "clang-format"
command = "clang-format"
args = ["-i", "-style=file"]
patterns = ["*.cpp", "*.h", "*.hpp"]

[[checks]]
name = "trailing-whitespace"
command = "grep"
args = ["-Pl", "[[:space:]]+$"]
patterns = ["*"]

[exclude]
paths = ["third_party/", "build/", ".git/"]

[output]
local_hook = true
github_actions = true
)";
      std::cout << "[INFO] created " << config_path << "\n";
      return 0;
    }

    auto cfg = load_config(config_path);
    auto repo_root = find_git_root();

    if (subcmd == "install" && cfg.generate_local_hook) {
      auto script = generate_local_hook(cfg);
      if (install_local_hook(repo_root, script)) {
        std::cout
            << "[INFO] pre-commit hook installed at .git/hooks/pre-commit\n";
      } else {
        std::cerr << "[ERROR] failed to write hook\n";
        return 1;
      }
    }

    if (subcmd == "generate-gha" || cfg.generate_gha) {
      auto yml = generate_github_actions(cfg);
      if (write_github_actions(repo_root, yml)) {
        std::cout << "[INFO] github action workflow generated at "
                     ".github/workflow/sniffercommit.yml\n";
      } else {
        std::cerr << "[ERROR] failed to write github action worflow\n";
        return 1;
      }
    }
  } catch (const std::exception &error) {
    std::cerr << "Error: " << error.what() << "\n";
  } catch (...) {
    std::cerr << "Unknown fatal error occurred\n";
    return 1;
  }

  return 0;
}
