#include "sniffercommit/precommit_domain.hpp"

#include <fmt/format.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <string>

#include "sniffercommit/project_config.hpp"

namespace sniffercommit::precommit {

static std::string regex_escape(const std::string& s) {
  std::string out;

  for (char c : s) {
    switch (c) {
      case '\\':
      case '.':
      case '+':
      case '*':
      case '?':
      case '[':
      case ']':
      case '^':
      case '$':
      case '(':
      case ')':
      case '{':
      case '}':
      case '|':
        out += '\\';
        break;
      default:
        break;
    }

    out += c;
  }

  return out;
}

std::string generate_hook(const project::ProjectConfig& cfg) {
  std::string exclude_pattern = "^.NO_MATCH$";
  if (!cfg.exclude_paths.empty()) {
    std::ostringstream oss;
    for (size_t i = 0; i < cfg.exclude_paths.size(); ++i) {
      if (i > 0) oss << "|";
      oss << regex_escape(cfg.exclude_paths[i]);
    }
    exclude_pattern = "(" + oss.str() + ")";
  }

  std::string execution_block;

  if (cfg.parallel) {
    execution_block = "declare -a PIDS=()\n";
    execution_block += "declare -A PID_TO_NAME=()\n";

    for (const auto& check : cfg.checks) {
      std::string cmd = check.command;

      for (const auto& arg : check.args) {
        cmd += " \"" + arg + "\"";
      }

      std::string patterns;
      for (const auto& p : check.patterns) {
        patterns += " \"" + p + "\"";
      }

      execution_block += fmt::format(
          "( run_check \"{}\" {} {} ) &\n"
          "PID=$!\n"
          "PIDS+=($PID)\n"
          "PID_TO_NAME[$PID]=\"{}\"\n",
          check.name, cmd, patterns, check.name);
    }

    execution_block += R"(
if [[ ${#PIDS[@]} -gt 0 ]]; then
    EXIT_CODE=0
    for pid in "${PIDS[@]}"; do
        if ! wait "$pid"; then
            echo "[sniffercommit] [ERROR] ${PID_TO_NAME[$pid]} failed" >&2
            EXIT_CODE=1
        fi
    done
    if [[ $EXIT_CODE -eq 0 ]]; then
        echo "[sniffercommit] [INFO] All checks passed."
    else
        echo "[sniffercommit] [ERROR] One or more checks failed."
    fi
    exit $EXIT_CODE
fi
)";
  } else {
    for (const auto& check : cfg.checks) {
      std::string cmd = check.command;

      for (const auto& arg : check.args) {
        cmd += " \"" + arg + "\"";
      }

      std::string patterns;
      for (const auto& p : check.patterns) {
        patterns += " \"" + p + "\"";
      }

      execution_block +=
          fmt::format("run_check \"{}\" {} {} || EXIT_CODE=$?\n", check.name, cmd, patterns);
    }

    execution_block += "exit $EXIT_CODE\n";
  }

  return fmt::format(
      R"(#!/usr/bin/env bash
# Generated by sniffercommit v0.1.0 | DO NOT EDIT MANUALLY
# Execution mode: {}
# Project: {}
set -uo pipefail

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -vE '{}' || true)

if [[ -z "$FILES" ]]; then
    echo "[sniffercommit] No staged files to check."
    exit 0
fi

filter_by_patterns() {{
    local files="$1"; shift
    local patterns=("$@")

    if [[ ${{#patterns[@]}} -eq 0 ]]; then
        echo "$files"
        return
    fi

    echo "$files" | while IFS= read -r file; do
        [[ -z "$file" ]] && continue

        for pattern in "${{patterns[@]}}"; do
            if [[ "$file" == $pattern ]]; then
                echo "$file"
                break
            fi
        done
    done
}}

run_check() {{
    local name="$1"; shift
    local cmd="$1"; shift
    local patterns=("$@")

    echo "[sniffercommit] [$(date +%T)] [INFO] Running: $name"

    local filtered
    filtered=$(filter_by_patterns "$FILES" "${{patterns[@]}}")

    if [[ -z "$filtered" ]]; then
        echo "[sniffercommit] [SKIP] No matching files for $name"
        return 0
    fi

    local status=0

    while IFS= read -r file; do
        [[ -z "$file" ]] && continue

        if ! "$cmd" "$file" 2>&1; then
            status=$?
        fi
    done <<< "$filtered"

    if [[ "$cmd" == "grep" && $status -eq 1 ]]; then
        status=0
    fi

    if [[ $status -ne 0 ]]; then
        echo "[sniffercommit] [WARN] $name exited with status $status" >&2
    fi

    return $status
}}

EXIT_CODE=0
{}
)",
      cfg.parallel ? "PARALLEL" : "SEQUENTIAL", cfg.project_name, exclude_pattern, execution_block);
}

bool install(const std::filesystem::path& repo_root, const std::string& hook_content) {
  auto hooks_dir = repo_root / ".git" / "hooks";
  std::filesystem::create_directories(hooks_dir);

  auto hook_path = hooks_dir / "pre-commit";
  std::ofstream out(hook_path, std::ios::trunc);
  if (!out) {
    return false;
  }

  out << hook_content;
  out.close();

#ifndef _WIN32
  std::filesystem::permissions(
      hook_path,
      std::filesystem::perms::owner_all | std::filesystem::perms::group_read |
          std::filesystem::perms::group_exec | std::filesystem::perms::others_read |
          std::filesystem::perms::others_exec,
      std::filesystem::perm_options::replace);
#endif  // _WIN32
  return true;
}

bool validate_syntax(const std::string& hook_content) {
  auto temp_path = std::filesystem::temp_directory_path() / "sniffercommit_hook_check.sh";

  {
    std::ofstream out(temp_path);
    if (!out) {
      return false;
    }

    out << hook_content;
  }

  std::string cmd = "bash -n " + temp_path.string() + " 2>/dev/null";
  bool valid = (std::system(cmd.c_str()) == 0);

  std::filesystem::remove(temp_path);
  return valid;
}

bool uninstall(const std::filesystem::path& repo_root) {
  auto hook_path = repo_root / ".git" / "hooks" / "pre-commit";
  if (std::filesystem::exists(hook_path)) {
    return std::filesystem::remove(hook_path);
  }

  return true;
}

bool is_installed(const std::filesystem::path& repo_root) {
  auto hook_path = repo_root / ".git" / "hooks" / "pre-commit";
  return std::filesystem::exists(hook_path);
}

}  // namespace sniffercommit::precommit
