#include "sniffercommit/precommit_domain.hpp"

#include <fmt/format.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <random>
#include <sstream>
#include <string>
#include <system_error>
#include <utility>

#include "sniffercommit/project_config.hpp"

namespace sniffercommit::precommit {

static std::string regex_escape(const std::string& str) {
  std::string out;
  out.reserve(str.size() * 2);

  for (char chr : str) {
    switch (chr) {
      // NOTE: Regex metacharacters
      case '\\':
      case '.':
      case '+':
      case '*':
      case '?':
      case '[':
      case ']':
      case '^':
      case '$':
      case '(':
      case ')':
      case '{':
      case '}':
      case '|':
      // INFO: Bash metacharacters (command injection prevention)
      case '`':
      case '"':
      case '!':
      case '&':
      case ';':
      case '<':
      case '>':
      case '#':
      case '~':
      case '\n':
        out += '\\';
        break;
      default:
        break;
    }

    out += chr;
  }

  return out;
}

std::string generate_hook(const project::ProjectConfig& cfg) {
  std::string exclude_pattern = "^.NO_MATCH$";
  if (!cfg.exclude_paths.empty()) {
    std::ostringstream oss;
    for (size_t i = 0; i < cfg.exclude_paths.size(); ++i) {
      if (i > 0) {
        oss << "|";
      }
      oss << regex_escape(cfg.exclude_paths.at(i));
    }
    exclude_pattern = "(" + oss.str() + ")";
  }

  return fmt::format(
      R"(#!/usr/bin/env bash
# Generated by sniffercommit v0.2.1 | DO NOT EDIT MANUALLY
# Project: {}
set -uo pipefail

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -vE '{}' || true)

if [[ -z "$FILES" ]]; then
    exit 0
fi

exec sniffercommit run --staged
)",
      cfg.project_name, exclude_pattern);
}

bool install(const std::filesystem::path& repo_root, const std::string& hook_content) {
  auto hooks_dir = repo_root / ".git" / "hooks";
  std::filesystem::create_directories(hooks_dir);

  auto hook_path = hooks_dir / "pre-commit";
  std::ofstream out(hook_path, std::ios::trunc);
  if (!out) {
    return false;
  }

  out << hook_content;
  out.close();

#ifndef _WIN32
  std::filesystem::permissions(
      hook_path,
      std::filesystem::perms::owner_all | std::filesystem::perms::group_read |
          std::filesystem::perms::group_exec | std::filesystem::perms::others_read |
          std::filesystem::perms::others_exec,
      std::filesystem::perm_options::replace);
#endif  // _WIN32
  return true;
}

bool validate_syntax(const std::string& hook_content) {
  // NOTE: RAII guard to make sure temporary file always got deleted
  struct TempFileGuard {
    std::filesystem::path path;

    explicit TempFileGuard(std::filesystem::path path_data) : path(std::move(path_data)) {}

    ~TempFileGuard() {
      std::error_code err_code;
      std::filesystem::remove(path, err_code);
    }

    TempFileGuard(const TempFileGuard&) = delete;
    TempFileGuard& operator=(const TempFileGuard&) = delete;
    TempFileGuard(TempFileGuard&&) = default;
    TempFileGuard& operator=(TempFileGuard&&) = default;
  };

  std::random_device random_device;
  std::mt19937 gen(random_device());
  std::uniform_int_distribution<> dis(100000, 999999);
  auto temp_path = std::filesystem::temp_directory_path() /
                   fmt::format("sniffercommit_hook_check_{}.sh", dis(gen));

  TempFileGuard guard{temp_path};

  {
    std::ofstream out(temp_path);
    if (!out) {
      return false;
    }

    out << hook_content;
    out.close();

    if (!out.good()) {
      return false;
    }
  }

  std::string cmd = "bash -n " + temp_path.string() + " 2>/dev/null";
  return std::system(cmd.c_str()) == 0;  // NOLINT(bugprone-command-processor)
}

bool uninstall(const std::filesystem::path& repo_root) {
  auto hook_path = repo_root / ".git" / "hooks" / "pre-commit";
  if (std::filesystem::exists(hook_path)) {
    return std::filesystem::remove(hook_path);
  }

  return true;
}

bool is_installed(const std::filesystem::path& repo_root) {
  auto hook_path = repo_root / ".git" / "hooks" / "pre-commit";
  return std::filesystem::exists(hook_path);
}

}  // namespace sniffercommit::precommit
